# Generated by Django 5.1.1 on 2024-09-22 04:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('square', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BettingMarket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market_type', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('odds', models.DecimalField(decimal_places=2, max_digits=5)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='square.match')),
            ],
        ),
    ]
