# Generated by Django 5.1.1 on 2025-03-04 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('square', '0003_vipstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='vipstatus',
            name='price',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10),
        ),
    ]
