# Generated by Django 5.1.1 on 2024-09-24 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('square', '0005_remove_match_match_result_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchprediction',
            name='sport_type',
        ),
    ]
