# Generated by Django 5.1.1 on 2024-09-28 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('square', '0008_footballprediction_o_1_5_match_result_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='footballprediction',
            name='total_cards',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='footballprediction',
            name='total_corners',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
