# Generated by Django 5.1.1 on 2024-09-29 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('square', '0011_footballprediction_dc12_normalized_probability_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='footballprediction',
            name='dc1x_normalized_probability',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='footballprediction',
            name='dcx2_normalized_probability',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
