# Generated by Django 5.1.1 on 2024-11-18 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('square', '0014_siteinformation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteinformation',
            name='logo',
            field=models.ImageField(blank=True, help_text='The logo of the site.', null=True, upload_to='media/logos/'),
        ),
    ]
