# Generated by Django 5.1.1 on 2025-01-28 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('square', '0016_match_away_team_id_match_away_team_logo_match_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='feels_like',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='humidity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='rain',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='temperature',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='weather_description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='wind_speed',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
