# Generated by Django 5.1.1 on 2025-01-28 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('square', '0017_match_feels_like_match_humidity_match_rain_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='footballprediction',
            name='away_team_goals',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='footballprediction',
            name='correct_score_odds',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='footballprediction',
            name='correct_score_result',
            field=models.CharField(choices=[('waiting', 'Waiting'), ('won', 'Won'), ('lost', 'Lost')], default='waiting', max_length=50),
        ),
        migrations.AddField(
            model_name='footballprediction',
            name='home_team_goals',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
