# Generated by Django 5.1.1 on 2025-01-28 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('square', '0018_footballprediction_away_team_goals_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basketballprediction',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='square.match', to_field='match_id'),
        ),
        migrations.AlterField(
            model_name='footballprediction',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='square.match', to_field='match_id'),
        ),
        migrations.AlterField(
            model_name='tennisprediction',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='square.match', to_field='match_id'),
        ),
    ]
