# Generated by Django 5.1.1 on 2025-02-03 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('square', '0019_alter_basketballprediction_match_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='basketballprediction',
            name='away_team_expected_goals',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='basketballprediction',
            name='home_team_expected_goals',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='footballprediction',
            name='away_team_expected_goals',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='footballprediction',
            name='home_team_expected_goals',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tennisprediction',
            name='away_team_expected_goals',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tennisprediction',
            name='home_team_expected_goals',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
