# Generated by Django 5.1.1 on 2025-02-18 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('square', '0021_fixture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixture',
            name='score_fulltime_away',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
