# Generated by Django 5.1.1 on 2025-02-18 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('square', '0023_resultdate_fixture_result_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='updated',
            field=models.BooleanField(default=True),
        ),
    ]
