# Generated by Django 5.1.1 on 2025-02-18 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('square', '0024_match_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='updated',
            field=models.BooleanField(default=False),
        ),
    ]
