# Generated by Django 5.1.1 on 2025-03-02 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('square', '0027_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteinformation',
            name='logo',
            field=models.ImageField(blank=True, help_text='The logo of the site.', null=True, upload_to='logos/'),
        ),
    ]
