# Generated by Django 5.1.1 on 2025-03-02 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(blank=True, max_length=10, null=True)),
                ('flag', models.URLField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MatchDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('current', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TaskProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=255)),
                ('progress', models.FloatField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('successful', models.PositiveIntegerField(default=0)),
                ('failed', models.PositiveIntegerField(default=0)),
                ('total', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('league_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=50)),
                ('logo', models.URLField(blank=True, max_length=300, null=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.country')),
                ('seasons', models.ManyToManyField(related_name='leagues', to='backend.season')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_id', models.IntegerField(unique=True)),
                ('date', models.DateTimeField()),
                ('referee', models.CharField(blank=True, max_length=100, null=True)),
                ('timezone', models.CharField(max_length=50)),
                ('venue_name', models.CharField(blank=True, max_length=100, null=True)),
                ('venue_city', models.CharField(blank=True, max_length=100, null=True)),
                ('home_team_name', models.CharField(max_length=100)),
                ('home_team_logo', models.URLField(blank=True, max_length=300, null=True)),
                ('home_team_id', models.IntegerField(blank=True, null=True)),
                ('away_team_name', models.CharField(max_length=100)),
                ('away_team_logo', models.URLField(blank=True, max_length=300, null=True)),
                ('away_team_id', models.IntegerField(blank=True, null=True)),
                ('to_be_predicted', models.BooleanField(default=False)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='backend.league')),
                ('match_date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='backend.matchdate')),
            ],
        ),
    ]
