# Generated by Django 5.1.1 on 2024-11-18 21:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='league',
            name='logo',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_id', models.IntegerField(unique=True)),
                ('date', models.DateTimeField()),
                ('referee', models.CharField(blank=True, max_length=100, null=True)),
                ('timezone', models.CharField(max_length=50)),
                ('venue_name', models.CharField(max_length=100)),
                ('venue_city', models.CharField(max_length=100)),
                ('home_team_name', models.CharField(max_length=100)),
                ('home_team_logo', models.URLField(blank=True, max_length=300, null=True)),
                ('away_team_name', models.CharField(max_length=100)),
                ('away_team_logo', models.URLField(blank=True, max_length=300, null=True)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='backend.league')),
                ('match_date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='backend.matchdate')),
            ],
        ),
    ]
