# Generated by Django 5.1.1 on 2024-11-19 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_match_venue_city_alter_match_venue_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='to_be_predicted',
            field=models.BooleanField(default=False),
        ),
    ]
