# Generated by Django 5.1.1 on 2024-11-22 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_match_to_be_predicted'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='away_team_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='home_team_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
