# Generated by Django 5.1.1 on 2025-01-26 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_remove_taskprogress_analysis_progress_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TaskProgress_analysis',
        ),
        migrations.AddField(
            model_name='taskprogress',
            name='failed',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='taskprogress',
            name='successful',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='taskprogress',
            name='total',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
